name: SecSend Server
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Clone SecSend repository
      run: git clone https://github.com/aguinet/secsend.git
      
    - name: Add Cloudflare repository
      run: |
        sudo mkdir -p --mode=0755 /usr/share/keyrings
        curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
        echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
        sudo apt-get update
        
    - name: Cache apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cloudflared
        version: 1.0
        
    - name: Change to SecSend directory 
      run: ls -l secsend/
      
    - name: Rename docker.env.example
      run: mv secsend/docker.env.example secsend/docker.env
      
    - name: Run SecSend Docker container
      env:
        CF_TUNNEL_CERT: ${{secrets.CF_TUNNEL_CERT}}
        CF_TUNNEL_UUID: ${{secrets.CF_TUNNEL_UUID}}
        CF_TUNNEL_UUID_CONTENT: ${{secrets.CF_TUNNEL_UUID_CONTENT}}
        FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
        REPO: ${{ github.repository }}
      run: |
        mkdir ~/.cloudflared
        echo "${CF_TUNNEL_CERT}" > ~/.cloudflared/cert.pem
        touch tunnel-config.yml
        echo "${CF_TUNNEL_UUID_CONTENT}" > credentials.json
        echo "url: http://127.0.0.1:8000" >> tunnel-config.yml
        echo "tunnel: ${CF_TUNNEL_UUID}" >> tunnel-config.yml
        echo "credentials-file: credentials.json" >> tunnel-config.yml
        cloudflared tunnel --config tunnel-config.yml run ${CF_TUNNEL_UUID} &
        CLOUDFLARED_PID=$!
        echo "Cloudflare Tunnel started with PID $CLOUDFLARED_PID"
        docker run --env-file secsend/docker.env -p 8000:80 -v ~/data/:/data aguinet/secsend:v1.1.1

        commit_and_push() {
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A  # Stage all changes
          git reset -- tunnel-config.yml
          git reset -- credentials.json
          git reset -- logs/
          
          
          if ! git commit -m "Auto commit every 25 seconds [no ci]"; then
              echo "No changes to commit or commit failed"
              return 1
          fi
          
          for i in {1..3}; do
              if git push https://x-access-token:${FINE_GRAINED_PAT}@github.com/${REPO}.git HEAD:main --force; then
                  echo "Push successful on attempt $i"
                  return 0
              else
                  echo "Push failed on attempt $i, retrying..."
                  git pull --rebase
              fi
          done
          
          echo "Failed to push after 3 attempts"
          return 1
        }

        while true; do
          if ! commit_and_push; then
              echo "Commit and push failed, continuing without stopping the workflow"
          fi
          sleep 25
        done
