name: SecSend Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Clone SecSend repository
      run: git clone https://github.com/aguinet/secsend.git
      
    - name: Change to SecSend directory 
      run: ls -l secsend/
      
    - name: Rename docker.env.example
      run: mv secsend/docker.env.example secsend/docker.env
      
    - name: Run SecSend Docker container
      run: |
        docker run --env-file secsend/docker.env -p 8000:80 -v /path/to/data/storage:/data aguinet/secsend:v1.1.1
